### PR TITLE
Attempt to support Statamic v4

### PR DESCRIPTION
**Pull request by grantholle**
Here's a half-attempt to support Statamic v4.

I've got the tests somewhat passing, admittedly jumping a few versions of testbench. Statamic's APIs seem to have changed too, so I did my best to get things working. I'm not familiar enough with it to get much further.

When I try to perform the action in Statamic, the following error occurs:

```
Call to undefined method Statamic\\Structures\\CollectionTree::page() at duplicator/src/Actions/DuplicateEntryAction.php:115)
```

I see that in the `Tree` class there is a `pages()` function, but indeed no `page()`. I think it's close? Not sure.

### CODE REVIEW

**Review by duncanmcclean — APPROVED** [review]
Thanks for this!

I've fixed the test & copied across changes made in the Core version of this action (the one used for non-multi-sites).

**Comment by duncanmcclean** [comment]
Released as part of [v4.0.0](https://github.com/duncanmcclean/duplicator/releases/tag/v4.0.0).

**Comment by dominikradl** [comment]
Thanks for the super fast update! Is there a reason php >=8.2 is required?
Laravel 10 supports php >=8.1, would that be fine too?

**Comment by duncanmcclean** [comment]
> 

Ah, didn't realise this PR removed PHP 8.1 support. I've added it back in v4.0.1.

**Pull request merged**
